image: ubuntu:18.04

before_script:

odu_connect_deploy:

  stage: build
  script:
  - unset CI
  - apt-get update -y
  - apt-get -y install rsync openssh-server curl
  - apt-get -y install -y npm
  - curl -sL https://deb.nodesource.com/setup_13.x | bash -
  - apt-get -y install nodejs
  - apt-get -y install build-essential
  - export LC_ALL="C.UTF-8"
  - export LANG="en_US.UTF-8"
  - export LANGUAGE="en_US.UTF-8"

  - eval $(ssh-agent -t 5m -s)

  - ssh-add <(echo "$RSYNC_KEY")
  - mkdir "${HOME}/.ssh"
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - ssh-keyscan -H atria.cs.odu.edu >> ~/.ssh/known_hosts

  - npm install
  - npm run build

  - rsync -auvz -e "ssh" build/* 411yello@atria.cs.odu.edu:/home/411yello/secure_html/oduconnect
  - ssh 411yello@atria.cs.odu.edu chmod 755 /home/411yello/secure_html/oduconnect

  tags:
  - docker

  only:
  - master
